<?php
namespace app\index\controller;
use think\Controller;
use think\Db; //引用数据库功能库
use think\Session;  //引用SESSION功能库
use Qs\auth\qsAuth; //引用AUTH功能库
class Index extends Controller{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        Session::set('user.id',1);//设置Session保存用户ID用于验证
        //Session::clear();//清空Session
    }

    public function index()
    {
        $this->checkAuth_demo();//查看checkAuth_demo方法的效果
        dump($this->getKeyWord_demo());//查看getKeyWord_demo方法输出的信息
        //return '<style type="text/css">*{ padding: 0; margin: 0; } .think_default_text{ padding: 4px 48px;} a{color:#2E5CD5;cursor: pointer;text-decoration: none} a:hover{text-decoration:underline; } body{ background: #fff; font-family: "Century Gothic","Microsoft yahei"; color: #333;font-size:18px} h1{ font-size: 100px; font-weight: normal; margin-bottom: 12px; } p{ line-height: 1.6em; font-size: 42px }</style><div style="padding: 24px 48px;"> <h1>:)</h1><p> ThinkPHP V5<br/><span style="font-size:30px">十年磨一剑 - 为API开发设计的高性能框架</span></p><span style="font-size:22px;">[ V5.0 版本由 <a href="http://www.qiniu.com" target="qiniu">七牛云</a> 独家赞助发布 ]</span></div><script type="text/javascript" src="http://tajs.qq.com/stats?sId=9347272" charset="UTF-8"></script><script type="text/javascript" src="http://ad.topthink.com/Public/static/client.js"></script><thinkad id="ad_bd568ce7058a1091"></thinkad>';
    }

    /*
     * Auth:Qs
     * Name:DEMO--验证用户是否有打开该页面的权限
     * Time:2017/10/11 16:00
     */
    private function checkAuth_demo(){
        $uid=Session::get('user.id');//通过Session获取用户的ID
        $check=new qsAuth();//引用AUTH库
        if(!$check->check(getRuleName(),$uid)){
            $this->error('无权限操作',config('caiyuan_url'));
        }else{
            $result=Db::table('ecm_member')->where('user_id',Session::get('user.id'))->find();
            $this->assign('UserInfo',$result);
        }
    }

    /*
     * Auth:Qs
     * Name:DEMO--提取字符串里的高频次出现的词
     * Time:2017/10/11 16:00
     */
    private function getKeyWord_demo(){
        $text="定义一个字符串用测试关键词的测试提取";
        return getKeyWord($text);
    }

}
